name: Hprofile Actions Code test with SonarQube part2
on: workflow_dispatch
# this means it will only run when Run in github actions. Later we will use push as a trigger
jobs:
  Testing:
  # this is the job name
    #specify the runner to run the job. Ubuntu has a lot of stuff prebuilt. It will run a container
    runs-on: ubuntu-latest
    # ubuntu-latest runner by default does not have sonar scanner so this has to be installed.
    steps:
      - name: Code checkout
      # by default github actions does not automatically clone the source code to the runner. This has to be explicitly done.
        uses: actions/checkout@v4
        # this is found at github.com/marketplace under Actions and then Checkout
        # This will clone whatever is the source code where this is being executed to the github runner

      - name: Maven test
        run: mvn test
      
      - name: Checkstyle analysis
        run: mvn checkstyle:checkstyle

      ## Sonarcloud configuration: sonarcube is not on the runner by default
      ## we can use github actions in marketplace for sonarcube scanners
      ## First need to install jdk.  Try jdk 11 first but I think this has been deprecated for sonarcube
      ## https://github.com/marketplace/actions/setup-java-jdk
      # Setup java 11 to be default (sonar-scanner requirement as of 5.x)

      # - name: Set Java 11
      #   uses: actions/setup-java@v3
      #   with:
      #    distribution: 'temurin' 
      #    # See 'Supported distributions' for available options: Oracle, corretto(AWS), temurin (eclipse)
      #    java-version: '11'

      # i think sonarcube scanner requires jdk 17 at minimum. Also setup-java is now @v4, but use v3 per examples
      # https://github.com/marketplace/actions/sonar-scanner

      - name: Set Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      ## another variant is java 21

      # - name: Set Java 21
      #   uses: actions/setup-java@v4
      #   with:
      #     distribution: 'temurin' # See 'Supported distributions' for available options
      #     java-version: '21'

          
      # Setup sonar-scanner
      # https://github.com/marketplace/actions/sonar-scanner
      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7
        # this setups up the sonar-scanner cli tool in the runner

      # Run sonar-scanner from CLI on the runner
      # All these github secrets have been entered into github under this repo
      # /src is in our source code and where the java source code resides
      - name: SonarQube Scan
        run: sonar-scanner
            -Dsonar.host.url=${{ secrets.SONAR_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.sources=src/
            -Dsonar.junit.reportsPath=target/surefire-reports/ 
            -Dsonar.jacoco.reportsPath=target/jacoco.exec 
            -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
            -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/




